services:
  app:
    container_name: courier_backend
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongodb_container
    networks:
      - courier_network
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  mongodb_container:
    image: mongo:latest
    container_name: courier_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - courier_network

volumes:
  mongo_data:

networks:
  courier_network:
    driver: bridge
